guildxyz/guild.xyz

src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx

Closes #166 
- Users can now search mirror editions by pasting an address (it'll list all editions for that address) or by typing in the edition ID)
- Now MirrorFormCard is filled up with default data properly inside the edit drawers

MirrorFormCard improvements

---

src/hooks/useSubmit.ts
src/types.ts
src/utils/fetcher.ts

Closes #390 
Adds support for signatures with Ambire wallet.
With this method we have the possibility to display custom message in the sign request. Right now it just displays the same one everywhere, but this can easily be changes by specifying `message` in the hook call

Method based authentication

---

src/components/[guild]/hooks/useAutoStatusUpdate.ts
src/pages/[guild]/index.tsx

Update the user status on focus, when their membership is differs from the current access check.

Status update when membership and accessCheck has differences

---

README.md
src/requirements/Sismo/SismoForm.tsx
src/requirements/Sismo/hooks/useSismoBadges.ts

Sismo updated the endpoints to query the badges from. This PR update these endpoints.
The addresses of the contracts must also be updated to get the balance: 
- Polygon: 0xF12494e3545D49616D9dFb78E5907E9078618a34
- Gnosis: 0xa67f1c6c96cb5dd6ef24b07a77893693c210d846
- Goerli: 0xA251eb9Be4e7E2bb382268eCdd0a5fca0A962E6c
- Mumbai: 0xc3Ee5Aad6Fb987cF69a2EE7B3B2c92E21E42F34B
_Note: I also updated the document in the README as I encountered some issue installing the app on windows (#643)_

Update Sismo requirements

---

src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/DiscordCardSettings/components/RoleToManage/components/GuildifyExistingRole.tsx
src/components/[guild]/RolePlatforms/components/PlatformCard/components/useDiscordCardProps/useDiscordCardProps.tsx
src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/components/common/DiscordGuildSetup/components/ServerSetupCard/ServerSetupCard.tsx
src/hooks/useServerData.ts

Refactored the `useServerData` hook for the guildify component.
Removed `membersWithoutRole` property, because as far as I checked, we don't use.

Hotfix member count at discord role creation

---

src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
src/components/[guild]/hooks/useAccess.ts
src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
src/pages/_app.tsx

I couldn't write a HogQL query for the entire access check result, so I've added some extra arrays (`unconnectedPlatforms` and `platformsToReconnect`). I couldn't make a common funnel for all the platforms, as it would need different filters for the different platforms, and I couldn't find an option to do that. I think it's fine for now, as we mostly care about Twitter now
I had to move the `AccountModal` from `Web3ConnectionManger` to a more inner scope, so it can consume PostHogProvider. I could't move `PostHogProvider` to upper scope, since it also needs to consume `Web3ConnectionManger`

Posthog events for Twitter connection

---

package-lock.json
package.json
src/components/[guild]/EditGuild/components/FeatureFlags.tsx
src/components/[guild]/Requirements/components/GuildCheckout/DynamicPurchaseRequirement.tsx
src/components/[guild]/Requirements/components/GuildCheckout/PurchaseRequirement.tsx
src/components/[guild]/hooks/useNonPurchasableAssets.ts
src/pages/api/fetchPrice.ts
src/pages/api/nonPurchasableAssets.ts
src/requirements/Nft/NftRequirement.tsx
src/requirements/Token/TokenRequirement.tsx
src/utils/guildCheckout/constants.ts

**Changes**
- Removed the `PURCHASE_REQUIREMENT` feature flag (related backend PR: https://github.com/agoraxyz/guild-backend/pull/844)
- Removed the non-purchasable assets list which we created manually
- Created a `GET /api/nonPurchasableAssets` endpoint which retrieves the non-purchasable assets from Vercel KV
- Added the `useNonPurchasableAssets` hook, which calls this new endpoint
- Modified the `fetchPrice` endpoint so it stores non-purchasable assets in Vercel KV if we get an `INSUFFICIENT_ASSET_LIQUIDITY` error
- Refactored the `PurchaseRequirement` component and added a `DynamicPurchaseRequirement` component so I could extract the rendering logic into that one
- Added the `0x-api-key` header to the 0x API call, since it will be required from June

feat: Save non-purchasable assets to Vercel KV

---

src/components/[guild]/JoinButton.tsx
src/components/[guild]/JoinModal/JoinModal.tsx
src/components/[guild]/JoinModal/components/ConnectAccount.tsx
src/components/[guild]/JoinModal/components/ConnectPlatform.tsx
src/components/[guild]/hooks/useAccess.ts
src/components/[guild]/hooks/usePlatformsToReconnect.ts
src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount.tsx
src/types.ts

Backend now returns a `requiredPlatforms` field. Now we can use this in `JoinModal` to display join steps. Also adds reconnect option for these join steps, which is based on access check `errors` fields

Join modal improvements for hidden requirements/rewards

---

src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/hooks/useShouldLinkToUser.ts
src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
src/hooks/useKeyPair.ts

The usage of `localStorage` causes some invalid states. I think it makes sense not to use `localStorage` for this action, and instead use an SWR state, or a simple state in a context. In this PR, I've tried the latter
Seems to work fine, the problem is, that I don't remember why we implemented it with `localStorage` originally

address merge: remove `localStorage` usage

---

src/components/[guild]/JoinModal/hooks/useJoin.tsx
src/components/[guild]/JoinModal/hooks/useOauthPopupWindow.ts

We have quite a lot of OAuth errors, that suggest that the provided authorization code is invalid or expired. Since we are supporting OAuth before wallet connection in the join modal, I'm trying to measure the largest time differences between the creation of the code, and the join request

PostHog events for measuring the time difference of OAuth code creation and join request

---

package-lock.json
package.json
src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/hooks/useEagerConnect.ts
src/connectors/coinbaseWallet.ts
src/connectors/gnosis.ts
src/connectors/index.ts
src/connectors/metaMask.ts
src/connectors/walletConnect.ts

This PR aims to make WalletConnect connections persistent by only connecting eagerly to the last used connector

Eager connection only for last used connector

---

src/components/create-guild/CreateGuildContext.tsx

~~Telegram guild creation currently fails when using the growth template, because it adds the Telegram reward to both roles by default. This PR aims to fix this issue by only adding the Telegram reward to one of the roles~~
I realized this is a problem with GitHub and Google as well, not just Telegram, so I've changed it to only include the second reward if the platform is Discord

Fix non-discord templated guild creation

---

src/components/[guild]/Requirements/components/BlockExplorerUrl.tsx
src/requirements/Nft/NftRequirement.tsx

This PR includes some small UI changes according to feedback here: https://discord.com/channels/697041998728659035/1143520047344652339/1144229221737189496
- `NftRequirement`: display the id, which the requirement is checking for, and use "a(n)" instead of "the" for `ERC1155`
- `BlockExplorerUrl`: Checks if the current requirement is either `ERC721` or `ERC1155`, and has a `data.id` field and if it does, use a link directly to that id

ERC-1155 UI changes

---

src/components/[guild]/AddRewardButton/AddRewardButton.tsx
src/components/[guild]/CreatePoap/AddPoapPanel.tsx
src/components/[guild]/CreatePoap/components/EditPoapRole/EditPoapRole.tsx
src/platforms/Poap/DeactivatePoapMenuItem.tsx

- Moved `CreatePoapContext` to a higher level, so we can properly display POAP data inside the `PoapPreview` components
- Fixed the default value for the `logic` field inside `EditPoapDrawer`
- Fixed `DeactivatePoapMenuItem` - we've sent an invalid parameter so users couldn't deactivate POAPs

POAP hotfixes

---

src/components/[guild]/CreatePoap/components/PoapRoleCard/PoapRoleCard.tsx
src/components/[guild]/RoleCard/RoleCard.tsx
src/components/[guild]/hooks/useGuild.ts
src/hooks/useSWRWithOptionalAuth.ts
src/pages/[guild]/index.tsx

In some cases, we have invalid data as the guild edit form's `defaultValues`. This happens when the drawer mounts before the guild data is fetched. In this case, the statically generated guild data is used, which can contain invalid data
This bug can't be consistently reproduced, but performing the following actions, and then refreshing the site until invalid data appears in the drawer can produce the bug
1. Open a guild in which you are admin
2. Add a new admin to the guild
3. Start refreshing the site until invalid data appears in the drawer
- `useSWRWithOptionalAuth` now returns an `isSigned` parameter that tells if the returned data came from a signed request's response
- Removes the statically generated data from signed data's fallback in the guild page's `getStaticProps`. This means …

Fix invalid form default values

---

src/hooks/useSWRWithOptionalAuth.ts

Due to https://github.com/agoraxyz/guild.xyz/commit/add059fe49efd926f106ed099a090abffb5b99bb, guild data was `undefined` for the duration of the authenticated request. This PR fixes this by binding the unauthenticated request's `shouldFetch` to `authenticatedResponse.data`, so it only stops fetching once we have authenticated data

hotfix: optional auth SWR error

---

package-lock.json
src/components/[guild]/EditGuild/EditGuildDrawer.tsx
src/components/[guild]/EditGuild/components/Admins/Admins.tsx
src/components/[guild]/EditGuild/hooks/useEditGuild.ts
src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
src/types.ts
src/utils/fetcher.ts
src/utils/handleSubmitDirty.ts

- Linear issue: https://linear.app/guildxyz/issue/GUILD-1066/fe-for-new-entities
- Discord thread: https://discord.com/channels/697041998728659035/1086006153365954600
- Guild edit now uses `handleSubmitDirty`
- Because of this, I had to include the `if (data.tags)` condition
- `useEditGuild`: Similarly to the hook for roles, it now separates contact, admin, and featureFlag requests from the main guild update request. It became massive, we might be able to abstract some of the logic away, but I'm not sure if it is important now
- `handleSubmitDirty` had to be tweaked once again :harold: The reason is that we only send the requests once the user hits save (we don't send an admin deletion immediately when the user presses the delete button. We could, lmk, if it should work that way, for now …

Separate requests for contacts, admins and featureFlags

---

src/components/_app/AddressLinkProvider.tsx
src/components/_app/KeyPairProvider.tsx
src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/hooks/useShouldLinkToUser.ts
src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx
src/pages/_app.tsx

Users currently can't link new addresses to their current profile,  because it seems like properties inside `addressLinkParams` are not defined. It happens because we store these values inside `Web3ConnectionManager`, but we use them in `KeyPairProvider`, which is **not** wrapped inside the connection manager provider.
1. Connect your wallet to Guild.xyz
2. Open the account modal, and click on "+ Link address"
3. Try linking another wallet address
4. It just won't work (we don't show an error toast, or anything else)
I extracted the `addressLinkParams` state in its own context and moved it above `KeyPairProvider`.

fix: put `addressLinkParams` in its own context

---

src/components/_app/KeyPairProvider.tsx
src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx

The keypair wasn't invalidated when the user switched to another wallet, so we sent an invalid public key to our API. I added the userId to the SWR key in this PR, so it'll be regenerated on wallet change.

fix: add userId to generatedKeyPair SWR key

---

src/requirements/ContractState/ContractStateForm.tsx
src/requirements/ContractState/ContractStateRequirement.tsx
src/requirements/ContractState/hooks/useAbi.ts
src/utils/handleSubmitDirty.ts
src/utils/mapRequirements.ts
src/utils/preprocessRequirements.ts

This PR adds support for the `CONTRACT` requirement type on all supported networks by allowing the users to fill out the form manually instead of selecting values from select inputs. The original functionality still works if we can fetch the contract ABI from the API.

feat(ContractStateForm): define values manually

---

src/components/[guild]/SetVisibility.tsx

I think we could wrap the `SetVisibility` buttons in `PulseMarker`s until the user doesn't click on them. It's a small change, but maybe this way our users would notice that we released this new feature for everyone.

feat(SetVisibility): add PulseMarkers

---

src/components/[guild]/AddRewardButton/AddRewardButton.tsx

Visibility was hard-coded to `PUBLIC` on the `POST /v2/guilds/:id/guild-platforms` endpoint, but it'll accept detailed role data from now, so I implemented the necessary changes in this PR.

feat(AddRewardButton): send detailed rolePlatform data

---

src/components/[guild]/Requirements/components/GuildCheckout/MintGuildPin/components/ActivateGuildPinForm.tsx
src/components/[guild]/hooks/useGuild.ts
src/components/[guild]/hooks/useRole.ts
src/requirements/Guild/GuildRequirement.tsx
src/types.ts

Added these 2 new hooks, so we don't fetch the guild data from the `/v2/guilds/:id/guild-page` endpoint inside `GuildRequirement`.

feat: `useSimpleGuild` & `useRole` hooks

---

src/components/[guild]/EditGuild/components/TagManager.tsx
src/utils/handleSubmitDirty.ts

We only checked if a form field value is truthy with a logical not operator inside `handleSubmitDirty`, so we actually filtered out boolean checkbox values & empty strings too (empty string is a valid form field value e.g. for a guild description), so I added a type check, let me know @cs-balazs if you think this is a good solution for the issue.

fix(edit guild): handle boolean fields properly

---

src/components/[guild]/EditGuild/components/Events/EventInput.tsx
src/components/[guild]/EditGuild/components/SocialLinks.tsx
src/utils/handleSubmitDirty.ts

The issue:
We can't delete the social and event links from the guild editor drawer.
Context and Expected Behaviour:
When we delete a link, we should send the rest to the backend because it will delete the links not in the request. 
The solution has two parts.
Part 1:
When we set the field to 'undefined' it won't be dirty. So I added an option to set them as dirty.
Part 2:
- We need to check the dirty fields to see if one of them is a key from 'DIRTY_KEYS_TO_KEEP'
- We set all the fields dirty to send to the backend.
- The rest of the current algorithm will filter the 'undefined' field as of now.
- As a result, we will send the fields not dirty as dirty with the current value and won't send the deleted.
Edge case:
The fix is not perfect, unfortunately, because it doesn't work when there is …

check dirty keys to keep when one of them is deleted.

---

src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
src/connectors.ts

I didn't find a way to detect Safe context like we did before, instead added a new `isInSafeContext` state, which is toggled to true, when the Safe connector is connected. This works because in order for a Safe app to work, it needs to auto-connect to the Safe account (which the wagmi connector seems to do by default, unlike the web3-react one). Therefore if I disconnect my Safe account, I can reconnect from the modal, and if I'm outside the context, I won't see the Safe option, as the connector didn't auto-connect

Wagmi Safe fix

---

src/platforms/Discord/DiscordCardMenu/components/DiscordCaptchaSwitch.tsx

This PR should fix the runner error's, when a Guild Admin switches the Discord captcha on and off.

Adding platformGuildId property to DiscordCaptchaSwitch

---

src/hooks/useSWRWithOptionalAuth.ts
src/pages/explorer.tsx

The data wasn't invalidated properly in `useYourGuilds` after successful guild creation, so I modified the mutator function inside `useSWRWithOptionalAuth`

fix(useSWRWithOptionalAuth): use mutate properly

---

src/components/[guild]/EditGuild/components/ColorPicker.tsx

[Linear issue](https://linear.app/guildxyz/issue/GUILD-2053/guild-color-change-bug)
It didn't work in the case when the color code was typed (or pasted) into the input field. Picking a color with the color picker seemed to work fine
The PR adds a `shouldDIrty: true` to the `setValue` call of the input field's `onChange`, so the value is included in the request

[GUILD-2053] - Color change fix

---

src/requirements/Allowlist/AllowlistForm.tsx

[Linear issue](https://linear.app/guildxyz/issue/GUILD-2055/support-empty-allowlist)
This PR makes the field non-required, so submitting a nullish value is allowed. In this case, the BE will still assign an empty array to `data.addresses`

[GUILD-2055] - Empty allowlist

---

src/requirements/Guild/components/Role.tsx

[Linear issue](https://linear.app/guildxyz/issue/GUILD-2054/guild-role-requirement-ui-bug)
This PR adds a new case to the `mergedGuildOptions` `useMemo`, which is when the search result is still being fetched, but the `foundGuild` value is truthy, which fixes a small glitch if we search for a guild, which the `foundGuild` already has

[GUILD-2054] - Role requirement - Guild option fix

---

src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx

[Linear issue](https://linear.app/guildxyz/issue/GUILD-2058/role-edit-drawer-save-button-bug)
The image change was only detected when the upload was finished, so there was a small delay between starting the upload and showing the save button. Since the save button handles the awaiting of the image upload, it seemed enough to just also show the footer when an upload is in progress

[GUILD-2058] - Role image upload save button fix

---

src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
src/components/common/GitHubGuildSetup.tsx
src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx

[Linear issue](https://linear.app/guildxyz/issue/GUILD-2074/github-guild-creation-fix-wrong-scope-error)
- Since there is no exact way to tell if a reauth is needed, or the user simply doesn't have any repos, this PR modifies the error alert to account for both cases
- There are three minor bugs I've found on the way:
- The skeleton's `key` values were wrong, I believe they all were undefined, instead of the intended index values
- When selecting a platform on the create-guild page, the modal didn't open when a platform connection also happened
- The user SWR state contained invalid data when a reauth happened, because the mutation just appended the platformUser object to the array

[GUILD-2074] - Fix GitHub reauth alert

---

src/components/[guild]/Tabs/GuildTabs.tsx
src/pages/[guild]/events.tsx

The navigation home tab from events tab when fetching the events was failed or not done causes navigation to the guild.xyz/undefined guild page.

fix(GuildTabs): debug&fix "/undefined" page

---

src/components/[guild]/activity/ActivityLogAction/components/ActionLabel.tsx
src/components/[guild]/activity/ActivityLogAction/components/ClickableTagPopover/components/ViewInCRM.tsx
src/components/[guild]/activity/ActivityLogContext.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/ActivityLogFiltersContext.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/DateRangeInput.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/FilterTag.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/RewardSuggestions.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/RoleSuggestions.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/FiltersInput.tsx
src/components/[guild]/activity/ActivityLogFiltersBar/components/Suggestions.tsx
src/pages/superadmin/activity.tsx

- new `superadmin/activity` url
- show 404 page if user is not superadmin
- in `ActivityLogContext`,  the `isUserActivity` prop is changed to `activityLogType` ("all",  "guild", and "user" activity logs)
- suggestions are rendered according to the `activityLogType`, moved to a separate `Suggestions` component
- fix for reward filter tags - after selecting a suggestion, they were not visible in the filter; now they are
---

feat: create superadmin activity log page

---

src/requirements/WalletActivity/WalletActivityForm.tsx

- Linear issue: [GUILD-2276](https://linear.app/guildxyz/issue/GUILD-2276/remove-unsupported-chains-from-wallet-activity)
- Discord thread: [bugs > Wallet activity - testnets?](https://discord.com/channels/697041998728659035/1201883761822670878)
Compared the supported chans list [on the frontend](https://github.com/guildxyz/guild.xyz/blob/main/src/requirements/WalletActivity/WalletActivityForm.tsx) and [in guild-gate](https://github.com/guildxyz/guild-gate/blob/main/src/requirements/covalent/types.ts). Removed unsupported entries from the frontend.

chore(wallet activity): Remove Goerli, Mumbai, X1 testnet

---

src/requirements/Fuel/FuelForm.tsx

Just a small text change to make the requirement more clear. It cannot check nfts at the moment.

Rename Fuel token balance req to make it more clear

---

src/components/[guild]/Requirements/components/HiddenRequirementAccessIndicator.tsx
src/components/[guild]/RoleCard/components/AccessIndicator/AccessIndicator.tsx

Gate will return `access:false` with `PLATFORM_CONNECT_INVALID` & `PLATFORM_NOT_CONNECTED` errors from now, so we should check for falsy values (instead of `null`) where we use requirement access in if statements / filters / etc.

fix(access check): check for falsy value instead of `null`

---

src/components/common/Layout/components/NavMenu/NavMenu.tsx
src/components/explorer/hooks/useRestoreScroll.ts
src/components/explorer/hooks/useScrollRestoration.ts
src/pages/explorer.tsx

I implemented a custom scroll restoration for the explorer page.
The built-in scroll restoration functioned only with backward navigation, such as using `router.back()` or the browser's back button. However, our "Back to explorer" link doesn't operate in this manner; it directs us to the `/explorer` URL instead of navigating back.
Additionally, the standard scroll restoration is affected by the "Your guilds" list, as it loads after the scroll position has been restored, altering the expected position.
Note that I had to implement an undesirable delay in the manual scroll restoration. This is because the built-in restoration and our custom solution currently execute simultaneously. Without this delay, the built-in mechanism would override our manual approach.
If the built-in scroll …

fix: scroll restoration in guild explorer

---

next-env.d.ts
package-lock.json
package.json
src/components/[guild]/Requirements/components/RequirementAccessIndicator.tsx
src/requirements/Allowlist/AllowlistForm.tsx
src/requirements/Allowlist/AllowlistRequirement.tsx
src/requirements/requirements.ts

- `RequirementAccessIndicator`: Turned out that a missing email is also returned as a platform error, so I added a condition for that as well. Started to get ugly, so added a const for the messages
- Added a `type` selector for the allowlist form with options `EVM and Fuel addresses` and `Email addresses`
- Validation uses `z.string().email()` just to be sure that it validates using the same email rules, as the schema used on BE
- Companion PRs:
- Gate: https://github.com/guildxyz/guild-gate/pull/715
- Core: https://github.com/guildxyz/guild-backend/pull/1369

[GUILD-2561] - Email allowlist

---

src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
src/platforms/rewards.tsx
src/requirements/Allowlist/AllowlistForm.tsx
src/requirements/Allowlist/AllowlistRequirement.tsx
src/requirements/Allowlist/components/AllowlistFormInputs.tsx
src/requirements/Email/EmailForm.tsx

[Linear](https://linear.app/guildxyz/issue/GUILD-2599/smaller-email-allowlist-improvements) - [Discord](https://discord.com/channels/697041998728659035/1221827375910621286/1222193169320382606)
- Show ALLOWLIST_EMAIL as an option under the email category as well
- Show connect button on requirement card
- For this, I've moved some code to a separate component
- Change EMAIL colorScheme to blue

[GUILD-2599] - Email allowlist improvements

---

src/components/[guild]/hooks/useGuild.ts
src/components/[guild]/hooks/useRole.ts

Sometimes we fetched the guild / role unnecessarily in the guild requirement display component, so I added some extra logic to these hooks: we check the `guild-page` cache before fetching the entities, and if we find the necessary data in this cache, we just return it from there.

`useGuild` & `useRole` optimization

---

src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/hooks/useLoginWithGoogle.ts

- Perform forced (`disconnectFromExistingUser`) connection
- This way, the Google account will always be linked to the user with the WaaS wallet
- Fixes a problem, when the Google account didn't immediately appear in the account modal after an initial login
- This bug was likely introduced in the OAuth rework PR, probably the hook performed the mutation before that rework. Now we perform the mutation after the connection in this `useSubmit` with the `userId` taken from the keypair submission request

Google login force connection & mutation fix

---

src/components/[guild]/EditGuild/components/FeatureFlags.tsx
src/components/[guild]/Tabs/GuildTabs.tsx
src/components/[guild]/messages/SendNewMessage/SendNewMessage.tsx
src/components/[guild]/messages/SendNewMessage/components/MessagingRateLimitAlert.tsx
src/components/common/Layout/components/Account/components/Web3Inbox/Web3InboxMessage.tsx

We'd like to release the messaging feature for every guild, but we have pretty strict rate limits, so we'll allow guild admins to send 1 message per day (per guild) for now & display an info alert for them if they reached this limit.

feat: messaging rate limit alert

---

src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/hooks/useAutoReconnect.ts
src/pages/_app.tsx

Unfortunately wagmi's `reconnectOnMount` was pretty unreliable, and the `isConnected` prop wasn't in sync with the `status` prop either, so we decided to implement a custom `useAutoReconnect` hook instead.

feat: useAutoReconnect hook

---

src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx

Display a general injected wallet if we can't detect an EIP-6963 compatible wallet.
Closes #1161

fix(WalletSelectorModal): add a general injected wallet

---

package-lock.json
package.json
src/requirements/Farcaster/FarcasterForm.tsx
src/requirements/Farcaster/FarcasterRequirement.tsx
src/requirements/Farcaster/components/FarcasterTextToInclude.tsx
src/requirements/requirements.ts

[Linear](https://linear.app/guildxyz/issue/GUILD-2759/farcaster-have-a-specific-text-in-usernamebio-as-requirement) - [Discord](https://discord.com/channels/697041998728659035/1224822723226636328)
- https://github.com/guildxyz/guild-backend/pull/1400
- https://github.com/guildxyz/guild-gate/pull/749
- Add components for `FARCASTER_USERNAME` and `FARCASTER_BIO` requirements

[GUILD-2759] - Farcaster username & bio requirements

---

src/components/[guild]/JoinModal/hooks/useActiveMembershipUpdate.tsx

Sometimes we get errors (e.g. `PLATFORM_CONNECT_INVALID`) in `requirementError` instead of `userLevelErrors`, so I added a fallback in `useActiveMembershipUpdate`

feat(useActiveMembershipUpdate): fallback to `requirementError`

---

src/components/_app/Web3ConnectionManager/Web3ConnectionManager.tsx
src/components/_app/Web3ConnectionManager/components/WalletLinkHelperModal.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
src/components/common/Layout/components/Account/components/AccountModal/components/LinkAddressButton.tsx

Move the modal with the helper video to the `Web3ConnectionManager` (so we only render it once), and also showing it only when the user already picked a connector. We also don't trigger an EVM wallet connection when the user starts the link address flow, because it was confusing for Fuel users.

refactor: improve the link address flow

---

src/wagmiConfig/waasConnector.ts

[BugSnag](https://app.bugsnag.com/guild-1/guild-dot-xyz/errors/6620f998aac2d10008772921?filters%5Bevent.unhandled%5D=true&filters%5Bevent.since%5D=30d&filters%5Bapp.release_stage%5D=production) - [Linear](https://linear.app/guildxyz/issue/GUILD-2818/waas-debugging)
- Issue 1: It wasn't possible to switch chains when connecting with WaaS
- This one comes from BugSnag
- Issue 2: The initial chain was `undefined` instead of `1`

fix(waas connector): chain handling

---

src/hooks/useOAuthResultToast.ts

- Issue 1: The toast is shown twice on OAuth errors, this is fixed by removing `toast` from the dependency array
- Issue 2: The `replace` call produces next js errors, which are coming to [BugSnag in a large quantity](https://app.bugsnag.com/guild-1/guild-dot-xyz/errors/6620cc8205e2280008de05f7?filters%5Bevent.unhandled%5D=true&filters%5Bevent.since%5D=30d&filters%5Bapp.release_stage%5D=production&filters%5Berror.status%5D=for_review)

fix(useOAuthResultToast): remove double toast & query param interpolation errors

---

fixWaas.js
mockWaas.js
package.json
src/wagmiConfig/waasConnector.ts

- We have quite a few `Failed to load chunk` errors, this PR aims to fix that
- The dynamic import itself was a workaround for this build error:
- `TypeError [ERR_IMPORT_ASSERTION_TYPE_MISSING]: Module ".../node_modules/@coinbase/waas-sdk-web/dist/versions.json" needs an import attribute of type "json"`
- This PR introduces a different workaround, so we can import non-dynamically
- Adds a `fixWaas.js` script, which replaces the `varsion.json` imports of the relevant files with the correct type assertion
~~Draft until tested on preview~~ Tested it, the build is successful, and functionality is working

fix(waas): use non-dyamic import

---

src/requirements/Allowlist/AllowlistRequirement.tsx

- Thought about moving this logic inside `RequirementConnectButton`, but I think this is specific to the email allowlist, because it depends on GOOGLE connection as well, not only the EMAIL connection, what do you think?
- [Linear](https://linear.app/guildxyz/issue/GUILD-2756/dont-show-connect-button-on-email-allowlist-requirement-if-user-has)

fix(email allowlist): hide the connect button if access is granted

---

src/components/[guild]/AddRewardButton/AddRewardButton.tsx
src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/components/common/ReconnectAlert.tsx
src/components/create-guild/CreateGuildButton.tsx
src/components/create-guild/CreateGuildIndex.tsx
src/components/create-guild/MultiPlatformGrid/components/CreateGuildDiscord.tsx
src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
src/components/create-guild/hooks/useCreateGuild.tsx

- Added events in the general DC add flow, plus some extra events, which are specific to guild creation, and reward addition to an existing guild
- Session recordings are started when the user initially selects discord in either flow. Not sure if these recordings are sampled by default
- One of the events is fired in a `useEffect` in `NotAdminError`. It seemed like a simple way to do it, but we might want to consider a refactor, let me know what you think
- Some events are duplicated with different names. This is because I'm not sure, which events are used, so didn't want to change the names, but wanted to stick to the same prefix for all the relevant events. But now I'm having second thoughts if it is worth it, so I think we might want to just stick to the existing events

[GUILD-2867] - Discord setup PostHog events

---

src/components/common/Button.tsx
src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/components/common/GitHubGuildSetup.tsx
src/components/common/GoogleGuildSetup/GoogleGuildSetup.tsx
src/hooks/usePopupWindow.ts
src/hooks/useServerData.ts
src/hooks/useServerPermissions.ts

- With some experimentation, revalidating the server data with `refreshInterval: 2000` seemed inconsistent, we can't guarantee that revalidation happens, when we want it to
- Instead, I added an `onClose` callback to `usePopupWindow` which fires when the popup is closed
- Note that this only works if we have a valid `windowInstance` object. I don't think this is a huge issue, since we used this same object for telling if the popup is open anyway
- Added `shouldRetryOnError: false` to `useServerData`'s SWR call, it seemed unnecessary to revalidate if this request fails
- Also, I've seen that gateables is also revalidated every 10 seconds, not sure why that is needed, the only thing I can think of is to handle if a server is created during the guild creation flow, which I think is an …

[GUILD-2900] - Fix add bot button

---

src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/components/common/DiscordGuildSetup/components/PermissionAlert.tsx
src/components/create-guild/MultiPlatformGrid/components/CreateGuildDiscord.tsx
src/hooks/useServerPermissions.ts

- Added a `PermissionAlert` component, which appears, when there are missing permissions after a bot is added (this is checked in the `onClose` callback). The `Administrator` permission is ignored from this check, as that is not relevant, and can't be granted through the OAuth page

feat(discord setup): permission alert after adding bot

---

src/components/[guild]/Requirements/RoleRequirements.tsx
src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
src/components/[guild]/collect/components/RequirementsCard.tsx
src/components/[guild]/collect/hooks/useNftDetails.ts
src/hooks/useUsersGuildPins.ts
src/pages/[guild]/collect/[chain]/[address].tsx
src/pages/_error.tsx
src/pages/api/nft/[chain]/[address].ts
src/pages/api/nft/collectors/[chain]/[address].ts
src/types.ts
src/utils/ipfsToGuildGateway.ts
src/wagmiConfig/index.ts

This PR aims to fix several problems on the Collect NFT page:
- the biggest change is that we use our own API key during ISR on this page, so we can properly determine if the reward actually doesn't exist (in this case, we can return a 404 response), or it's a hidden/private reward
- added a new serverless endpoint (`/api/nft/[chain]/[address]`): we fetch the immutable onchain data for the NFT on this endpoint, and cache it for a very long time, so we won't need to re-fetch it on the client & we also pre-populate the SWR cache with it during ISR, so we'll be able to load render the page data on client side much faster
- fixed `RoleRequirements`: we only show a skeleton loader when the requirements are actually loading
- fixed the SWR mutation in `useCreateNft`, it probably didn't work at …

feat: rework the Collect NFT page

---

src/components/[guild]/AccessHub/AccessHub.tsx
src/components/[guild]/AccessHub/components/AccessedGuildPlatformCard.tsx

When a user switched from an admin account to a non-admin account on a guild's page, they sometimes got a client-side error. The root of the issue is that we essentially created & rendered the card components inside the `AccessHub` component (where we mapped `accessedGuildPlatforms`) - seems this was a bad practice, since we didn't trigger re-renders immediately in some cases, e.g. when a user switched accounts. 
I solved the issue by creating an `AccessedGuildPlatformCard` component and using it inside the access hub.

refactor(AccessHub): `AccessedGuildPlatformCard` component

---

src/components/[guild]/hooks/useGuild.ts
src/pages/[guild]/analytics.tsx
src/pages/[guild]/forms/[formId]/responses.tsx
src/pages/[guild]/members.tsx

- fixed the `useGuild` hook: its `data` was undefined initially when we loaded a client-side only page, so the hook returned an error & we rendered the 404 fallback page
- fixed some `undefined` page titles

fix(authenticated pages): don't fallback to 404 unintentionally

---

src/components/_app/Web3ConnectionManager/hooks/useAutoReconnect.ts
src/hooks/useSubmit/useSubmit.ts

- Fixes connection to Safe wallet inside a Safe app
- If we are inside a Safe app (checked by `safeConnector.getProvider()`), we try auto-connecting to that
- Additional small fix: only request chain-switching if the `walletClient`'s current `chainId` is different

[GUILD-2708] - Fix Safe wallet connection

---

src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddDiscordPanel.tsx
src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/components/create-guild/MultiPlatformGrid/components/CreateGuildDiscord.tsx

- Don't call `/gateables` before clicking the Discord card
- Included a small refactor. Some of it is not necessary for the `/gateables` optimization, just seemed reasonable
- Moved some form state inside `DiscordGuildSetup`
- The component now works with a fixed form structure instead of getting more params. I think this makes sense, as we use it in 2 places, and the structure is the same for them

[GUILD-2901] - `/gateables` call optimization & Discord setup refactor

---

src/components/[guild]/JoinModal/hooks/useConnectPlatform.ts
src/components/[guild]/JoinModal/hooks/useFetchUserEmail.ts

- After a GOOGLE platform, if the user doesn't have an EMAIL connection, we revalidate the email data, because the Google account's email might got added to the user as EMAIL as well

[GUILD-2755] - Autoconnect email after google connection

---

src/components/[guild]/AccessHub/components/CampaignCards/components/EditCampaignModal.tsx
src/components/[guild]/AddAndOrderRoles/components/AddRoleDrawer.tsx
src/components/[guild]/AddRewardButton/hooks/useSetRoleImageAndNameFromPlatformData.ts
src/components/[guild]/CreateCampaignModal/CreateCampaignModal.tsx
src/components/[guild]/EditGuild/EditGuildDrawer.tsx
src/components/[guild]/Requirements/components/RequirementImageEditor.tsx
src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/SetTokenStep.tsx
src/components/[guild]/crm/FilterByRoles/components/AddHiddenRoleButton.tsx
src/components/create-guild/BasicInfo/BasicInfo.tsx
src/hooks/usePinata/usePinata.ts
src/hooks/useSubmit/useSubmit.ts
src/platforms/SecretText/SecretTextDataForm/components/RewardImagePicker.tsx

[Linear](https://linear.app/guildxyz/issue/GUILD-2863/fix-usepinata-hook)
- Tested the changes by adding a `useEffect(() => console.log("onUpdate", onUpdate), [onUpdate])` at the end of `usePinata` before the `return`. Then visiting the `/create-guild` page, and on the `BasicInfo` section, I've made some blur-s on the inputs. The blurs caused both of the `usePinata` hooks to log the message again (plus there were an initial ~8 logs)
- I think the reason is that the form's context changed and that we used anonymous functions without `useCallback`
- Changes in this PR:
- `useSubmit`: Wrapped the returned `onSubmit` function in a useCallback - [a8dc2a0](https://github.com/guildxyz/guild.xyz/commit/a8dc2a0c4e0e920c6b210b56e40782893a557d34)
- `usePinata`
- Moved the submit function out of the …

[GUILD-2863] - usePinata optimization

---

src/components/[guild]/forms/responses/FormResponsesTable.tsx
src/hooks/useOAuthResultToast.ts
src/hooks/useQueryState.ts
src/pages/[guild]/members.tsx
src/pages/_app.tsx

Seems like the methods from the `useRouter` hook aren't referentially stable, so when we included them in a `useEffect`'s dependency array, they caused infinite re-renders. Here is the related Next.js issue: https://github.com/vercel/next.js/issues/18127
Since they won't fix it in the pages directory, I just removed the router methods from dependency arrays.

fix: don't use `replace` from `useRouter` in dependency arrays

---

src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
src/components/[guild]/JoinModal/hooks/useMembershipUpdate.tsx
src/components/[guild]/JoinModal/utils/getGuildPlatformsOfRoles.ts
src/components/[guild]/RoleCard/components/EditRole/hooks/useEditRole.ts
src/components/[guild]/collect/hooks/useCollectNft.ts
src/components/[guild]/forms/FillForm.tsx
src/components/create-guild/hooks/useCreateGuild.tsx
src/components/create-guild/hooks/useCreateRole.tsx
src/hooks/useCustomPosthogEvents.ts
src/platforms/Forms/hooks/useFormSubmissions.tsx
src/platforms/Gather/hooks/useClaimGather.tsx
src/platforms/PolygonID/components/MintableRole.tsx
src/platforms/SecretText/hooks/useClaimText.tsx
src/platforms/Token/hooks/useCollectToken.tsx

- Linear: https://linear.app/guildxyz/issue/GUILD-3003/reward-collection-by-guild-type
- Added a `useCustomPosthogEvents` hook. I think this is useful for events that get sent from multiple places. This way is is not possible to make a typo, or forget a param, or something similar
- Added events:
- `reward created`: Sent when a guildPlatform is created by: guild creation, role creation, rolePlatform creation, or guildPlatform creation
- `reward granted`: When a membership update is successful, we check the `newMembershipRoleIds` field, and send this event for all the rolePlatforms of those roles
- `reward claimed`: Sent when a reward is claimed by the `/claim` endpoint & when a form is submitted & when a polygonId is minted

[GUILD-3003] - Reward-related posthog events

---

src/components/[guild]/AddRewardButton/hooks/useSetRoleImageAndNameFromPlatformData.ts

This hook ran too many times & called the Pinata API constantly, which is not the expected behavior. As a quick fix, I added an extra `alreadyUploaded` state & an early return, and also added a condition so we don't re-upload the image if we already uploaded it to IPFS. Let me know if you have a better idea, not sure how could we handle this properly.

fix(useSetRoleImageAndNameFromPlatformData): add early return to useEffect

---

src/components/[guild]/AccessHub/hooks/useEditGuildPlatform.ts
src/components/[guild]/RoleCard/components/EditNFTDescriptionModal.tsx
src/platforms/Poap/PoapCardButton.tsx
src/platforms/Poap/PoapCardMenu.tsx
src/platforms/Poap/UploadMintLinksModal.tsx
src/platforms/UniqueText/UniqueTextDataForm.tsx

Our API rewrites the `platformGuildData` object when we edit it, so we always need to send both the unmodified and modified data. I refactored this hook, so we won't need to handle this logic where we use the `useEditGuildPlatform` hook.

refactor(useEditGuildPlatform): send the whole `platformGuildData` object to our API

---

src/hooks/useSetKeyPair.ts
src/hooks/useSubmit/useSubmit.ts

- Adds an alternative message-generation function `getSiweMessage` which is used when sending a request to the verify endpoint
- More details on the BE PR: https://github.com/guildxyz/guild-backend/pull/1421

[GUILD-1380] - Sign-in-with-Ethereum

---

src/components/[guild]/AccessHub/components/usePlatformAccessButton.tsx

[Linear](https://linear.app/guildxyz/issue/GUILD-3083/invalid-discord-server-link)
- Once we use zod schemas more for BE-side input validation & sanitization, we can solve this easily on that side as well, which would be a better solution
- For now, I think this solution will be fine, as for now this is mainly intended to fix the issue in this Guild: https://guild.xyz/degenwars

[GUILD-3083] - fix: sanitize discord invite links

---

src/components/[guild]/AddRewardButton/hooks/useAddRoleRewards.ts
src/components/[guild]/AddRewardButton/hooks/useSubmitAddReward.ts
src/components/[guild]/NoRolesAlert.tsx
src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/AddRoleRewardModal.tsx
src/components/[guild]/RoleSelector.tsx
src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
src/hooks/useServerPermissions.ts
src/platforms/components/SelectRoleOrSetRequirements.tsx

This PR adds the functionality for selecting DC servers, which are already added to a guild
- Both adding with the guild page _add reward_ button, and to an existing role should work, if you try the preview out, please check out both
- When adding through the guild page _add reward_ button, only those roles should be listed, which don't already have the selected server as a reward

[GUILD-3074] - List already added DC servers in setup grid

---

src/components/[guild]/hooks/useUser.ts
src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx

- This seems to be a much simpler solution. One less `useEffect` always feels like a good idea
- Tested by:
- I connected my wallet, refreshed the page, and the modal appeared
- I invalidated my key, and reloaded the page, and both the toast appears, and the modal opened
- Temporarily added `/explorer` to the ignored routes array, and the modal no longer open

[GUILD-2197] - refactor: move complicated `useEffect` logic in `useUserPublic`

---

src/requirements/VisitLink/VisitLinkForm.tsx

The `URL` API by default converts elements in the *origin* to lowercase.

[GUILD-3132] fix: convert only relevant elements of the url to lowercase

---

src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/GoogleLoginButton/components/CopyWaaSPrivateKey.tsx
src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
src/wagmiConfig/waasConnector.ts

[Linear](https://linear.app/guildxyz/issue/GUILD-3104/coinbase-data-import) - [Discord](https://discord.com/channels/697041998728659035/1169587223956570232/1247473523816140821)
- This is needed for the user linked in the Linear ticket, and once we transition to Smart Wallet, we will need this option for current waas users
- Can be tested by:
1. Connecting with waas
2. Taking note of the address
3. Exporting the private key
4. Importing the wallet into MetaMask (or other wallet)
5. Checking if the imported wallet's address is the same as the one noted earlier

[GUILD-3104] - WaaS: Change backup data export feature to private key export

---

src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddTokenPanel/components/PoolStep.tsx
src/requirements/WalletActivity/components/ControlledNumberInput.tsx

When creating a token reward, the flow got stuck at the pool creation. It would create the pool, but not move on.
Turns out we had a min value validation on the amount field that should not be there.

fix: token reward setup stuck at pool creation

---

src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx

- We commonly have bug reports where this alert's description is empty
- This PR changes up the description conditions a bit
- I've just put everything after `err?.message ?? ` in parentheses
- Previously the first part of the conditions meant `(err?.message ?? typeof err?.error === "string") ? err?.error : ...`
- Not it is `err?.message ?? (typeof err?.error === "string" ? err?.error : ...)`

fix(WalletSelectorModal): error alert description

---

src/components/[guild]/hooks/useUser.ts

[Linear](https://linear.app/guildxyz/issue/GUILD-3226/useuserpublic-open-walletselectormodal-onerror-and-dont-retry-on-error)
- There is a small bug with account verification:
1. Log out of your current account
2. Login with a fresh wallet (the easiest way is to do this with a new Smart Wallet)
3. Don't click the verify button, instead refresh the page
4. When the page refreshes, you should see that your wallet is connected, but you don't get a verification modal
- This PR aims to fix this by opening the modal in `useUserPublic`'s `onError`
- Also sets `shouldRetryOnError` to false, as it is expected to return an error if the user doesn't exist, there is no need to fetch 5 more times

[GUILD-3226] - `useUserPublic` fixes

---

src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/WalletSelectorModal.tsx

Users sometimes try to link the address which they currently use to their account - this makes no sense & this was an unhandled path (we opened the link address modal without a "Link address" button). This PR aims to solve this by showing an info toast with some guidance & hiding the Link Address modal in this case.

fix(WalletSelectorModal): show toast if user tries to link their current address

---

src/requirements/Payment/PaymentForm.tsx
src/requirements/Payment/components/RegisterVaultForm/RegisterVaultForm.tsx
src/requirements/Payment/components/RegisterVaultForm/hooks/useRegisterVault.ts

This PR prevents error: https://jam.dev/c/d88f9e28-bddf-46f4-a8a7-5a668a43b3c8
Added validation to make sure the token precision is not exceeded, `parseFloat` is replaced by string as JS numbers are unreliable for this kind of use case.

Improve and fix `PaymentForm`, prevent JS scientific notation conversion

---

src/requirements/Points/PointsRequirement.tsx

Turns out we weren't able to display points from external guilds, so this PR aims to fix that! I also changed the `useGuild(guildId)` call to a `useSimpleGuild(guildId)` + a `GET /guilds/:guildId/guild-plaftorms`, because it's more efficient than fetching the whole `/guild-page` of another guild.

fix(PointsRequirement): display points from external guilds

---

src/pages/[guild]/collect/[chain]/[address].tsx

We had a client-side error in cases when the NFT reward wasn't public in a guild. I think we can safely "leak" the `guildPlatform` here, since NFTs are public by default (they're on chain rewards), but let me know if you have any other suggestions!

fix(Collect page): always add the relevant guildPlatform to the SWR cache

---

README.md
next.config.js
package.json
tsconfig.build.json
tsconfig.json

The idea is to set `strict` & `strictNullChecks` to `true` in our TS config, but set them to `false` (their current value) in the pre-commit hook & during build, so we could gradually fix the issues caused by these settings during development, but our app will build without errors in prod.

feat: enable `strictNullChecks` during development

---

src/components/[guild]/activity/ActivityLogAction/components/ActionLabel.tsx
src/components/[guild]/activity/ActivityLogContext.tsx
src/components/[guild]/activity/constants.ts

The `join guild` action was a child action of `click join on web` before, but now it's also a parent action, so we can use the former one. The original `click join on web` was a bit misleading, since it is triggered for access checks too.
Relevant backend PR: https://github.com/guildxyz/guild-backend/pull/1529

feat(activity log): don't fetch `click join on web` actions

---

src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddSecretTextPanel.tsx
src/rewards/PolygonID/components/ConnectDIDModal.tsx
src/rewards/PolygonID/components/MintPolygonIDProofProvider.tsx
src/rewards/SecretText/EditSecretTextModal.tsx
src/rewards/SecretText/SecretTextDataForm/SecretTextDataForm.tsx
src/rewards/SecretText/SecretTextDataForm/components/PublicRewardDataForm.tsx
src/rewards/SecretText/SecretTextDataForm/index.ts
src/rewards/SecretText/SecretTextDataForm/types.ts

- **fix(SecretText): resolve circular dependency inside rewards**
- **fix(PolygonID): resolve circular dependency inside rewards**

resolve circular deps inside rewards

---

src/v2/components/ui/Dialog.stories.tsx
src/v2/components/ui/Dialog.tsx

Made the overlay scrollable & added a Dialog story so we can easily preview all sizes / variants.

`Dialog` improvements

---

src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/FarcasterProfile.tsx

- It is now possible, that a Farcaster connection doesn't need a QR code, instead connects an existing key to the user
- This PR handles this case, when we don't need to show a QR code
- BE: https://github.com/guildxyz/guild-backend/pull/1541

[GUILD-3399] - Farcaster connection can reuse existing approved keys

---

package-lock.json
package.json
scripts/bundleAnalyzer.mjs

Extended the default bundle analyzer by default path and path check, also removed prettier and eslint from `package.json` run scripts.

ci: add analyzer and biome check run script

---

src/components/[guild]/EditGuild/EditGuildDrawer.tsx
src/components/[guild]/EditGuild/components/Events/EventInput.tsx

Important: this is a hotfix. We'll need to write a proper schema for this form in our types package & use Zod for validating every field in the edit guild form.

fix(EditGuildDrawer): validate `eventSources` with Zod

---

src/components/[guild]/AccessHub/components/CampaignCards/CampaignCards.tsx
src/components/[guild]/AccessHub/components/CampaignCards/components/CampaignCardMenu.tsx
src/components/[guild]/AccessHub/components/CampaignCards/components/EditCampaignModal.tsx
src/components/[guild]/AccessHub/components/CampaignCards/hooks/useEditRoleGroup.ts
src/components/[guild]/CreateCampaignModal/components/CampaignForm.tsx
src/components/[guild]/[group]/EditCampaignButton.tsx
src/types.ts

Admins can now hide page cards from their guild's home page with the `hideFromGuildPage` prop. These pages will be returned by our API, but we don't display them on our UI (so the goal of this feature is not to handle the actual visibility of the pages, just to clean up the access hub a bit).

feat: hidden pages

---

src/app/(marketing)/profile/[username]/page.tsx
src/app/(marketing)/profile/_components/EditContributions.tsx
src/app/(marketing)/profile/_components/Profile.tsx
src/app/(marketing)/profile/_components/ProfileOwnerGuard.tsx
src/app/(marketing)/profile/_hooks/useContributions.tsx
src/app/(marketing)/profile/_hooks/useCreateContribution.tsx
src/app/(marketing)/profile/_hooks/useDeleteContribution.tsx
src/app/(marketing)/profile/_hooks/useUpdateContribution.tsx
src/app/(marketing)/profile/_hooks/useUpdateProfile.ts
src/app/(marketing)/profile/_server_actions/revalidateContributions.ts
src/hooks/useSetKeyPair.ts
src/hooks/useSubmit/types.ts
src/hooks/useSubmit/useSubmit.ts

- **refactor: redirect to error and fetch per guild**
- **feat: add optimistic update to contributions**

add optimistic update for edit contributions and profile

---

src/components/[guild]/EditGuild/components/UrlName.tsx

Allow appending dash `-` character to the end of the url for convenience
Linear issue: [GUILD-3545](https://linear.app/guildxyz/issue/GUILD-3545/guild-url-name-accept-too)
> Note: I don't feel like it's a bad limitation, but `slugify` doesn't allow neighbouring dashes.

feat: allow appending dash "-" to the end of url name

---

src/app/(marketing)/profile/[username]/page.tsx
src/app/(marketing)/profile/_components/OperatedGuilds.tsx
src/app/(marketing)/profile/_components/Profile.tsx
src/app/(marketing)/profile/_utils/selectOperatedGuilds.ts

- **feat: add operated guild cards**
- **chore: remove non-retrievable cards**
- **feat: render operated guilds on server**
- **fix: cache the correct endpoint for operated guilds**
- **chore: adjust experience card**

Add operated guilds and improve `/profile`

---

src/v2/components/ui/IconButton.stories.tsx
src/v2/components/ui/IconButton.tsx

Implemented this component for 2 reasons:
- We'll refactor the `Button` component & it'll receive left and right icon as a prop, so I'd like to maintain a consistent API for this (we could technically use the button component & pass the icon as a child to it too, but then we'd probably forget to define the `aria-label` attribute, which is important for accessibility)
- I noticed that we have an `icon` and an `icon-sm` size variant in our `Button` component, which in my opinion clearly indicated that we might need a new component for these variants

feat: `IconButton` component & stories

---

src/v2/components/Web3ConnectionManager/WalletSelectorModal/WalletSelectorModal.tsx
src/v2/components/Web3ConnectionManager/hooks/useWeb3ConnectionManager.ts

Sometimes the wallet client is still `undefined` when the user clicks on the "Verify address" button, so the users gets on error. This PR aims to handle this edge case.

fix: handle loading wallet client

---

.env
src/app/(marketing)/profile/[username]/page.tsx
src/env.js

~~Until the new neynar endpoint is finished, remove the neynar call that causes error on profiles with farcaster~~
Use `guild.xyz` without subdomain for url when requesting neynar.
Error was caused by having a real href swapped by the new neynar route handler (`api/neynar`), which is required by URL constructor
```tsx
const neynarRequest = fcProfile && new URL(`${NEYNAR_BASE_URL}/user/bulk?fids=${fcProfile.fid}`, api)
```
[discord reference](https://discord.com/channels/697041998728659035/1192824841703784498/1293127450141786162)

fix: remove old neynar api call

---

src/static/customChains.ts

Switched from Blockscout to Etherscan, because I experienced issues with Blockscout

Blockscout -> Etherscan

---

src/app/api/leaderboard/route.ts
src/components/[guild]/leaderboard/LeaderboardPointsSelector.tsx
src/components/common/Layout/components/Footer.tsx

- export all users, not just the top 500
- fix typo in the export button's tooltip
- adjust the tooltip so it actually says it's an export button
- boy scout: remove unnecessary comma from the footer (again)

Leaderboard export improvements

---

package.json
src/app/layout.tsx
src/components/ui/Toaster.tsx
src/stories/Toast.stories.tsx

I wasn't sure if we should define custom styles for the toast icon (fixed size, for example), let me know what's your opinion on that!

feat: Toast component with Sonner

---

.github/workflows/code-check.yml
.husky/pre-commit
README.md
package.json

Since we're using it for local development, I guess we can try to use it here too.

feat: use Bun in the `code-check` GitHub Action

---

src/components/[guild]/collect/components/CollectNft/components/CollectNftButton.tsx
src/components/[guild]/collect/components/CollectNft/components/NftFeesTable.tsx
src/components/[guild]/collect/hooks/useCollectNft.ts
src/components/[guild]/collect/hooks/useGuildFee.ts
src/static/abis/guildRewardNFTFactory.ts

Feature implementation in the contracts: https://github.com/guildxyz/nft-reward-factory/commit/45b11d6b7802cbe3f81f7b509955e036752acbd3

feat(NFT-reward): add support for fee overrides
