guildxyz/guild.xyz

- src/pages/[guild].tsx
> Only render guilds by urlName

- src/components/[guild]/RequirementCard/RequirementCard.tsx
- src/components/[guild]/RequirementCard/hooks/useTokenImage.ts
- src/components/common/ChakraReactSelect/ChakraReactSelect.tsx
- src/components/common/ChakraReactSelect/CustomSelectOption.tsx
- src/components/create-guild/NftFormCard/NftFormCard.tsx
- src/components/create-guild/NftFormCard/hooks/useNfts.ts
- src/components/create-guild/NftFormCard/hooks/useNftsList.ts
- src/components/create-guild/PoapFormCard/PoapFormCard.tsx
- src/components/create-guild/PoapFormCard/hooks/usePoaps.ts
- src/components/create-guild/SnapshotFormCard/SnapshotFormCard.tsx
- src/components/create-guild/SnapshotFormCard/hooks/useSnapshots.ts
- src/components/create-guild/SnapshotFormCard/hooks/useSnapshotsList.ts
- src/components/create-guild/SnapshotFormCard/hooks/useStrategyParamsArray.ts
- src/components/create-guild/Symbol.tsx
- src/components/create-guild/TokenFormCard/TokenFormCard.tsx
- src/components/create-guild/hooks/useNftCustomAttributeNames.ts
- src/components/create-guild/hooks/useNftCustomAttributeValues.ts
- src/hooks/useTokens.ts
Closes #31 
Added an `isLoading` boolean prop to this components. If this prop is `true`, the select will render a spinner inside the options list.
> ChakraReactSelect improvements

- src/components/[group]/EditForm.tsx
- src/components/[guild]/EditForm.tsx
- src/components/common/Layout/Layout.tsx
- src/components/create/Description.tsx
- src/pages/[hall]/edit.tsx
- src/pages/[hall]/index.tsx
- src/pages/create-guild.tsx
- src/pages/create-hall.tsx
- src/pages/guild/[guild]/edit.tsx
- src/pages/guild/[guild]/index.tsx
- src/theme/components/input.ts
- src/theme/components/textarea.ts
> Halls & guilds - descriptions

- src/hooks/useTokens.ts
> useTokens - CELO and HARMONY token list URLs

- src/components/[guild]/RequirementCard/RequirementCard.tsx
- src/components/create-guild/Requirements/components/RequirementChainTypeText.tsx
> Requirement chain indicator UI fix

- src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
> Fixed whitelist textarea validation

- src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/BackgroundImageUploader.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorModePicker.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorPicker.tsx
- src/components/common/FormErrorMessage.tsx
- src/components/create-guild/IconSelector/components/PhotoUploader.tsx
- src/components/create-guild/LogicPicker/LogicPicker.tsx
- src/components/create-guild/NameAndIcon.tsx
- src/components/create-guild/PickRolePlatform/PickRolePlatform.tsx
- src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
- src/components/create-guild/Requirements/components/JuiceboxFormCard/JuiceboxFormCard.tsx
- src/components/create-guild/Requirements/components/MirrorFormCard/MirrorFormCard.tsx
- src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
- src/components/create-guild/Requirements/components/PoapFormCard/PoapFormCard.tsx
- src/components/create-guild/Requirements/components/SnapshotFormCard/SnapshotFormCard.tsx
- src/components/create-guild/Requirements/components/TokenFormCard.tsx
- src/components/create-guild/Requirements/components/UnlockFormCard/UnlockFormCard.tsx
- src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
> FormErrorMessage - collapse transition

- src/components/[guild]/EditButtonGroup/components/CustomizationButton/CustomizationButton.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationButton/components/ColorPicker.tsx
- src/components/[guild]/ThemeContext.tsx
> Fix first time appearance customization

- package-lock.json
- package.json
Closes #118 
More info here: https://github.com/EthWorks/useDApp/issues/320#issuecomment-990633636
> Fix crash on switching to an unsupported chain

- src/components/[guild]/RolesByPlatform/components/RoleListItem/RoleListItem.tsx
- src/components/common/DisplayCard.tsx
- src/components/common/GuildLogo.tsx
- src/components/common/Layout/Layout.tsx
- src/components/create-guild/IconSelector/components/PhotoUploader.tsx
> Image optimization

- next-env.d.ts
- src/hooks/useSubmit/useSubmit.ts
> Fix machine warnings

- src/pages/[guild]/index.tsx
> Sorting roles by members count

- src/pages/[guild]/index.tsx
> Fix getting 500 internal server error instead of 404 on unexisting guild urls

- src/components/[guild]/EditButtonGroup/components/AddRoleDrawer.tsx
We should wait for the next version of the BE before merging this PR!
Closes #191
> AddRoleDrawer - form reset fixes

- .env
- src/components/[guild]/EditButtonGroup/components/CustomizationModal/CustomizationModal.tsx
- src/components/[guild]/ThemeContext.tsx
- src/components/[guild]/hooks/useEdit.ts
- src/types.ts
TODO: switch back to the prod API before merging
Closes #193
> Updated Guild type & ThemeContext

- src/components/[guild]/Members/Members.tsx
- src/components/common/GuildAvatar.tsx
> Rendering members on scroll

- src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
> Fixed validation issues on NftFormCard

- src/components/[guild]/DeleteButton.tsx
- src/components/[guild]/EditButtonGroup/components/AddRoleDrawer.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationModal/CustomizationModal.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/BackgroundImageUploader.tsx
- src/components/[guild]/EditButtonGroup/components/CustomizationModal/components/RemoveBackgroundImage.tsx
- src/components/[guild]/EditButtonGroup/components/EditGuildDrawer.tsx
- src/components/[guild]/LeaveButton/LeaveButton.tsx
- src/components/[guild]/RequirementCard/components/Whitelist.tsx
- src/components/[guild]/RolesByPlatform/components/JoinButton/JoinButton.tsx
- src/components/[guild]/RolesByPlatform/components/RoleListItem/RoleListItem.tsx
- src/components/[guild]/RolesByPlatform/components/RoleListItem/components/EditRole.tsx
- src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/ConnectorButton.tsx
- src/components/common/Button.tsx
- src/components/common/CopyableAddress.tsx
- src/components/common/DiscardAlert.tsx
- src/components/common/Layout/components/Account/components/AccountButton.tsx
- src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
- src/components/common/Layout/components/Account/components/AccountModal/components/AccountConnections.tsx
- src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
- src/components/common/Layout/components/Account/components/NetworkModal/components/NetworkButton/NetworkButton.tsx
- src/components/common/LinkButton.tsx
- src/components/common/ModalButton.tsx
- src/components/create-guild/IconSelector/components/PhotoUploader.tsx
- src/components/create-guild/LogicPicker/components/LogicOption.tsx
- src/components/create-guild/PickRolePlatform/components/CustomDiscord/CustomDiscord.tsx
- src/components/create-guild/PickRolePlatform/components/PlatformOption.tsx
- src/components/create-guild/PickRolePlatform/components/TelegramGroup/TelegramGroup.tsx
- src/components/create-guild/Requirements/components/AddRequirementCard.tsx
- src/components/create-guild/Requirements/components/WhitelistFormCard.tsx
- src/components/create-guild/SubmitButton.tsx
> Custom Button component

- src/components/[guild]/Members/Members.tsx
- src/pages/[guild]/index.tsx
So the owner's address is always the first one
Closes #225
> Sorting members list

- src/components/[guild]/RequirementCard/RequirementCard.tsx
- src/components/[guild]/RequirementCard/components/Mirror.tsx
> Mirror requirements - displaying edition name

- src/components/[guild]/EditGuildButton/components/DeleteGuildButton/hooks/useDeleteGuild.ts
- src/components/[guild]/EditGuildButton/hooks/useEditGuild.ts
- src/components/[guild]/RolesByPlatform/components/RoleListItem/components/AccessIndicator/AccessIndicator.tsx
- src/components/create-guild/hooks/useCreate.ts
- src/hooks/useMatchMutate.ts
> Mutating guild list on guild create/edit/delete

- src/components/create-guild/CreateGuildName.tsx
> Don't validate name field by urlName on creation

- src/components/common/Layout/Layout.tsx
> fix: background height glitch

- src/components/common/StyledSelect/StyledSelect.tsx
> Fix: pasting address in the select inputs on mobile

- src/components/[guild]/EditGuildButton/components/UrlName.tsx
> fix: url name validation

- src/components/create-guild/Requirements/components/MinMaxAmount.tsx
- src/components/create-guild/Requirements/components/TokenFormCard.tsx
> MinMaxAmount add info tooltip & fix fractional amount support

- src/components/create-guild/Requirements/components/MinMaxAmount.tsx
> fix: MinMaxAmount formatting with regex

- src/components/create-guild/Requirements/components/AllowlistFormCard.tsx
> Allowlist - upload .txt/.csv

- src/pages/[guild]/index.tsx
> fix: Guild page - using AnimateSharedLayout

- src/components/create-guild/Requirements/components/NftFormCard/NftFormCard.tsx
> NftFormCard: add key-value inputs for Polygon NFTs

- src/components/create-guild/Requirements/components/GalaxyFormCard/GalaxyFormCard.tsx
> Search for private Galaxy campaigns

- src/components/[guild]/Requirements/components/OtterspaceRequirementCard.tsx
- src/components/create-guild/Requirements/components/ChainPicker.tsx
- src/components/create-guild/Requirements/components/OtterspaceFormCard/OtterspaceFormCard.tsx
- src/components/create-guild/Requirements/components/OtterspaceFormCard/hooks/useOtterspaceBadges.ts
> Otterspace integration - multichain support

- src/components/[guild]/ThemeContext.tsx
Removed Portal, so that the page renders properly on server-side too
> ThemeContext rework

- src/requirements/Galaxy/GalaxyForm.tsx
> Galxe integration - remove chain picker

- src/components/[guild]/Members/Members.tsx
- src/components/[guild]/Requirements/RoleRequirements.tsx
- src/components/[guild]/Requirements/components/ExpandRequirementsButton.tsx
- src/components/[guild]/Requirements/components/RequiementAccessIndicatorUI.tsx
- src/components/common/Section.tsx
- src/pages/[guild]/index.tsx
- src/pages/explorer.tsx
> Page speed optimization for big guilds

- src/requirements/Sound/SoundForm.tsx
- src/requirements/Sound/SoundRequirement.tsx
- src/requirements/Sound/components/SoundMinAmount.tsx
- src/requirements/Sound/components/SoundTopCollector.tsx
> Sound integration update

- src/utils/fetcher.ts
> Auth header flag

- src/components/[guild]/Requirements/RoleRequirements.tsx
- src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
- src/types.ts
- Added `isHidden: boolean` to the `Requirement` type
- Removed some type casts that are now unnecessary with the type change
> Add `isHidden` to `Requirement` & remove type casts

- src/components/[guild]/AccessHub/AccessHub.tsx
- src/components/[guild]/JoinModal/hooks/useJoin.tsx
- src/components/[guild]/LeaveButton/hooks/useLeaveGuild.ts
- src/components/[guild]/hooks/useAutoStatusUpdate.ts
- src/components/[guild]/hooks/useIsMember.ts
- src/components/_app/IntercomProvider.tsx
- src/components/explorer/hooks/useMemberships.ts
- src/pages/explorer.tsx
This PR adds optimistic SWR state mutations after join and leave to avoid populating backend cache with outdated data from the replica db
> Optimistic mutations after join and leave

- src/components/common/StyledSelect/StyledSelect.tsx
- src/requirements/Galaxy/GalaxyForm.tsx
- src/requirements/Galaxy/hooks/useGalaxyCampaigns.ts
- src/requirements/Juicebox/JuiceboxForm.tsx
- src/requirements/Juicebox/hooks/useJuicebox.ts
- src/requirements/Poap/PoapForm.tsx
- src/requirements/Poap/hooks/usePoaps.ts
- src/requirements/Snapshot/components/SpaceSelect.tsx
- src/requirements/Snapshot/hooks/useProposals.ts
From now we'll use the new `search` query param on our API
> feat: more effective search in requirement setup forms

- src/components/[guild]/Requirements/components/GuildCheckout/components/BuyTotal.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/FeesTable.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/PurchaseFeeAndTotal.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseAllowanceButton.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/buttons/PurchaseButton.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePayFee.ts
- src/components/[guild]/Requirements/components/GuildCheckout/hooks/usePurchaseAsset.ts
- src/pages/api/fetchPrice.ts
- src/utils/guildCheckout/utils.ts
So we can display a detailed fee breakdown for the user in the Guild Checkout flow
> feat: detailed FeeTable component

- src/requirements/WalletActivity/WalletActivityForm.tsx
add Base Goerli chain option to all types except the TX_VALUE ones
> feat(WalletActivity): support Base Goerli

- src/requirements/Galaxy/GalaxyForm.tsx
- src/requirements/Galaxy/GalaxyRequirement.tsx
- src/requirements/requirements.ts
> feat: `GALAXY_PARTICIPATION` requirement type

- src/requirements/WalletActivity/WalletActivityForm.tsx
- src/requirements/WalletActivity/WalletActivityRequirement.tsx
- src/requirements/WalletActivity/components/BlockNumberFormControl.tsx
- src/requirements/requirements.ts
- src/utils/preprocessRequirements.ts
> Covalent wallet activity requirements

- src/requirements/PoapPayment/gnosisAPiUrls.ts
As recommended by @yagopv here: https://github.com/5afe/safe-apps-list/issues/268#issuecomment-1687605093
> Fix safe api urls

- src/requirements/WalletActivity/WalletActivityForm.tsx
> Avalanche wallet activity with covalent

- src/components/[guild]/AddRewardButton/hooks/useAddReward.ts
- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
- src/platforms/ContractCall/ContractCallReward.tsx
- src/platforms/ContractCall/ContractCallRewardCardButton.tsx
New PostHog events:
| Event name | Info |
|---|---|
| useAddreward error | sending `guildId` and `error` in details |
| useCreateNft callStatic error | sending `error` in details |
| useCreateNft error | general error, after/during the actual contract call - sending `error` in details |
| Successfully created NFT | sending `chain` and `contractAddress` in details |
| Click on collect page link (ContractCallReward) | sending `guild` (`urlName`) in details |
| Click on collect page link (ContractCallRewardCardButton) | sending `guild` (`urlName`) in details |
> feat(NFT reward): add more PostHog events

- src/components/[guild]/hooks/useAccess.ts
(waiting for the support team to confirm the name of the custom intercom attribute)
> feat: send access check error codes to intercom

- src/hooks/resolving/useResolveAddress.ts
This is just a small improvement to avoid sending a lot of requests every time a page load (at least on guild / collect nft pages)
TODO:
> feat(useResolveAddress): save resolved name to IDB

- .env
- src/components/[guild]/Requirements/components/ConnectRequirementPlatformButton.tsx
- src/components/common/Layout/components/Account/components/AccountModal/components/SocialAccount/EmailAddress.tsx
- src/components/create-guild/Requirements/components/AddRequirement.tsx
- src/requirements/Email/EmailForm.tsx
- src/requirements/Email/EmailRequirement.tsx
- src/requirements/requirements.ts
This PR adds support for the upcoming email requirements
- Added `EMAIL` in the `REQUIREMENTS_DATA` list
- Added `EmailForm`, and `EmailRequirement` components
- Minor change in `AddRequirement` to support component as an icon
- [WIP] Changed `ConnectRequirementPlatformButton` to support email connection
- WIP, as this is not tested yet
> Email requirements

- src/requirements/Lens/LensForm.tsx
- src/requirements/Lens/LensRequirement.tsx
We just rebranded lenster.xyz to hey.xyz
https://twitter.com/heydotxyz/status/1707431312385253477
> chore: rename lenster to hey

- src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
- src/components/common/DrawerHeader.tsx
https://linear.app/guildxyz/issue/GUILD-1331/edit-role-dynamic-footer
> feat: UX improvement on role drawer footer

- next.config.js
- src/components/[guild]/EditGuild/EditGuildDrawer.tsx
- src/components/[guild]/EditGuild/components/Events/Events.tsx
- src/components/[guild]/Events/EventCard/EventCard.tsx
- src/components/[guild]/Events/EventCard/components/EventImage.tsx
- src/components/[guild]/Events/EventCard/components/JoinEventButton.tsx
- src/hooks/useGuildEvents.ts
https://linear.app/guildxyz/issue/GUILD-1102/link3
> feat: add link3 events

- src/connectors/index.ts
- src/hooks/useTokens.ts
- src/requirements/WalletActivity/WalletActivityForm.tsx
> feat: Polygon zkEVM support

- package-lock.json
- package.json
- src/components/[guild]/Requirements/components/RequirementDisplayComponent.tsx
- src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
Added an `InvalidRequirementErrorBoundary` component so we can display a fallback UI for invalid requirements & we can also log these errors in PostHog
> feat: InvalidRequirementErrorBoundary component

- src/chains.ts
- src/hooks/useTokens.ts
- src/requirements/WalletActivity/WalletActivityForm.tsx
- src/static/customChains.ts
- fix explorer scroll alpha
- added support for these scroll sepolia and scroll mainnet
> feat: scroll supports

- src/components/[guild]/Requirements/RoleRequirements.tsx
- src/components/[guild]/RoleCard/components/RoleRequirementsSection.tsx
- src/components/[guild]/RoleCard/index.ts
- src/components/[guild]/collect/components/RequirementsCard.tsx
- src/components/create-guild/ChooseTemplate/components/TemplateCard.tsx
- src/components/create-guild/ChooseTemplate/components/TemplateRequriements.tsx
- src/pages/[guild]/collect/[chain]/[address].tsx
Note: added a `transition` prop to `VirtualRequirements`, because for some reason the animation didn't work on the collect page without that :harold:
> feat(collect page): collapsible requirements

- src/components/_app/Web3ConnectionManager/components/WalletSelectorModal/components/FuelConnectorButtons.tsx
- src/components/_app/Web3ConnectionManager/hooks/useWeb3ConnectionManager.ts
- src/components/common/Layout/components/Account/components/AccountModal/AccountModal.tsx
- src/components/common/Layout/components/Account/components/AccountModal/components/AddressTypeTag.tsx
- src/components/common/Layout/components/Account/components/AccountModal/components/LinkedAddress.tsx
- src/hooks/useFuel.ts
- src/hooks/useSetupFuel.ts
- src/hooks/useUsersGuildPins.ts
- src/types.ts
- indicating fuel addresses in the account modal
- handling multiple fuel connectors & connecting with the right one
- fetching guild pins for evm accounts only (we'll need to refactor this hook later so we can handle fuel addresses & pins on fuel too)
> Fuel improvements

- src/static/customChains.ts
> Update "Ontology" to "Ontology EVM"

- src/components/[guild]/AddAndOrderRoles/AddAndOrderRoles.tsx
- src/components/[guild]/Onboarding/Onboarding.tsx
- src/components/[guild]/Onboarding/components/SummonMembers/SummonMembers.tsx
- src/components/[guild]/Onboarding/components/SummonMembers/components/SendDiscordJoinButtonAlert.tsx
- src/components/[guild]/Onboarding/components/SummonMembers/components/SendDiscordJoinButtonModal.tsx
- src/components/[guild]/RoleCard/components/EditRole/EditRole.tsx
- src/components/_app/PostHogProvider.tsx
- src/components/create-guild/CreateGuildButton.tsx
- src/components/create-guild/CreateGuildIndex.tsx
- src/components/create-guild/CreateGuildStepper.tsx
- src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
- src/components/create-guild/hooks/useCreateGuild.tsx
- src/pages/create-guild.tsx
https://linear.app/guildxyz/issue/GUILD-1835/add-posthog-metrics
> feat: guild creation flow posthog events

- src/utils/createAndAwaitJob.ts
- If the last GET haven't finished we should not call the GET again.
- If a GET took more than 3 seconds, we called the API again, creating more requests and more load. Now we wait until the last call is finished then wait 3 seconds.
- Also updated the error fields.
- The "Job not found" part should not happen in normal scenarios, only when the redis is manually flushed (by me).
You can check it here: https://guild-xyz-git-await-job-polling-zgen.vercel.app/our-guild
> Use await and loop for polling jobs

- .gitignore
- src/platforms/SecretText/SecretTextDataForm/SecretTextDataForm.tsx
- src/platforms/UniqueText/UniqueTextDataForm.tsx
[issue](https://linear.app/guildxyz/issue/GUILD-1512/secret-rewards-validate-texts-length)
> feat(Secret rewards): validate text(s)' length

- src/platforms/platforms.tsx
[GUILD-2046](https://linear.app/guildxyz/issue/GUILD-2046/add-loading-fallback-to-addplatformpanels)
> feat(Add reward): Add spinner to all AddPlatformPanel

- src/components/[guild]/activity/ActivityLogAction/components/MoreActions.tsx
- src/components/[guild]/activity/ActivityLogContext.tsx
Ready to merge once we use v2 joins in every* guild
> Don't filter SendReward/RevokeReward actions in audit log

- src/components/[guild]/activity/ActivityLogAction/components/ActionLabel.tsx
- src/components/[guild]/activity/ActivityLogContext.tsx
- src/components/[guild]/activity/constants.ts
- src/components/common/Layout/components/Account/components/Notifications/Notifications.tsx
> feat: add opt-in and opt-out actions to activity log

- src/utils/guildCheckout/constants.ts
- Linear issue: [GUILD-2145](https://linear.app/guildxyz/issue/GUILD-2145/guild-pin-ontology-evm)
- Discord thread: [forum > - 🚧 - Guild Pin](https://discord.com/channels/697041998728659035/1077188341562359868)
Added the chain to the supported chains object, no es mucho pero es trabajo honesto
> feat(Guild Pin): Ontology support

- src/components/[guild]/activity/ActivityLogContext.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/ActivityLogFiltersBar.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/GuildActivityLogFiltersBar.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/UserActivityLogFiltersBar.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/components/DateRangeInput.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/components/FilterTag/components/ActionSuggestons.tsx
- src/components/[guild]/activity/ActivityLogFiltersBar/index.ts
- src/components/[guild]/activity/constants.ts
- src/components/[guild]/crm/FilterByRoles/FilterByRolesLogicSelector.tsx
- src/components/common/RadioButtonGroup.tsx
- src/pages/[guild]/activity.tsx
- src/pages/profile/activity.tsx
> feat(ActivityLog): User & Admin actions tabs on guild activity log

- src/components/create-guild/Requirements/components/RequirementEditableCard.tsx
- src/requirements/index.ts
- src/requirements/requirements.ts
❗ The relevant backend PR should be merged first! https://github.com/guildxyz/guild-backend/pull/1243
> feat: allow customization for all requirement types

- src/requirements/Guild/GuildForm.tsx
- src/requirements/Guild/GuildRequirement.tsx
- src/requirements/Guild/components/Role.tsx
- src/requirements/requirements.ts
- src/types.ts
feat(Role): create RoleWithRangeFilter component
feat(Role): add filter to the options of the selectable roles
feat(GuildRequirement): add label to display the filter
feat(requirements): Add new GUILD_ROLE_RELATIVE requirement
feat(GuildRequirement): Add new HaveRoleRelative Component
> feat:Add filter to Guild-"have a role" requirement

- src/requirements/Mirror/MirrorForm.tsx
- src/requirements/requirements.ts
- Small UI change
- `MIRROR_COLLECT` is the default req type for Mirror
Please run it, it works locally but this is my first frontend pr 🙈
> Set MIRROR_COLLECT as the default req type for Mirror

- package-lock.json
- package.json
- src/components/[guild]/EditGuild/components/FeatureFlags.tsx
Workaround: put prop on select to opens top side, auto isn't working
> fix: Update react select to check if the menu positioning is solved

- src/components/[guild]/JoinModal/hooks/useJoin.tsx
- src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
How to reproduce: 
- create a guild with a hidden free entry role
- join the guild with a user (who is not an admin in the guild)
> fix(join flow): join guild with hidden roles

- src/components/create-guild/MultiPlatformGrid/components/MultiPlatformSelectButton.tsx
- Adding a Twitter link, then removing it results in a validation error in the guild creation request
> fix(MultiPlatformSelectButton): socialLinks field reset

- src/components/[guild]/DiscordBotPermissionsChecker.tsx
Before:
After:
I don't know css, so the spacing is terrible, I know.
> Show bot permissions in an unordered list

- src/components/[guild]/DiscordBotPermissionsChecker.tsx
- src/components/common/DiscordGuildSetup/components/DCServerCard.tsx
- src/hooks/useServerPermissions.ts
Needed to list existing invites in a server.
Related discussion: https://discord.com/channels/697041998728659035/1225061886513643520/1237750831454097500
> Add MANAGE_GUILD permission to bot invite link

- src/components/[guild]/hooks/useRequirement.ts
- src/requirements/Allowlist/AllowlistRequirement.tsx
- src/requirements/common/SearchableVirtualListModal.tsx
- We only get at maximum 10 addresses in a request
- We can pass a `search` query param to search in the allowlist
- Added a `useRequirement` hook to manage this logic
> [GUILD-2917] - Allowlist request optimization with searching

- src/hooks/useSubmit/useSubmit.ts
- Needed for https://github.com/guildxyz/guild-backend/pull/1484
> [GUILD-1838] - Always send `chainId` auth param

- src/components/[guild]/AddRewardButton/SelectRolePanel.tsx
To understand how people utilize this feature, I configured PostHog events to record the settings applied when they add rewards using the button.
> monitor add reward button usage

- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/ImagePicker.tsx
- src/components/[guild]/collect/components/CollectibleImage.tsx
- src/components/[guild]/collect/components/TiltCard.tsx
- src/pages/[guild]/collect/[chain]/[address].tsx
> feat: interactive `TiltCard` component

- src/components/create-guild/Requirements/components/ExistingRequirementEditableCard.tsx
- src/components/create-guild/Requirements/hooks/useCreateRequirement.ts
- src/components/create-guild/Requirements/hooks/useEditRequirement.ts
- src/requirements/Allowlist/AllowlistRequirement.tsx
- src/requirements/Allowlist/components/AllowlistFormInputs.tsx
- src/requirements/common/SearchableVirtualListModal.tsx
[Linear](https://linear.app/guildxyz/issue/GUILD-3142/fe-implementation)
- Upload allowlist files to GCS
- The uploaded file's ID is saved in the requirement's `.data.fileId` field
- The BE sends information on the processing status, and the number of processed addresses
> merge only once gate and core are both merged, and they work as expected
> [GUILD-3142] - Allowlist file processing

- src/components/[guild]/EditGuild/components/SocialLinks.tsx
The validation trigger is controlled in higher up the component tree and it is set to `onChange` which might be unpleasant.
> feat: autofill href if possible and validate

- src/components/[guild]/AddRewardButton/components/AvailabilitySetup.tsx
Either this, or showing a "Claim started" badge, but I thought that might be a bit redundant.
> fix: show full limit availability button

- src/components/[guild]/hooks/useGuild.ts
We always mutate the authenticated cache key in `useGuild`'s `onSuccess`, which is not correct, because if a user visits a guild page by the guild's ID (e.g. [guild.xyz/1985](https://guild.xyz/1985)), we just populate the authenticated cache with the unauthenticated data & don't call the `/guilds/:guildId` endpoint with auth, so guild admins can't see the secret/hidden requirements/roles/rewards.
> fix(useGuild): mutate the correct cache key

- src/env.js
Removed some unused env vars & added some comments / spacing in the env file, so it's more readable.
> cleanup(env): remove unnecessary variables & add comments

- src/requirements/Farcaster/FarcasterRequirement.tsx
Datablock replaced by link. I wonder if we should handle the undefined `data` cases when it isn't loaded.
> feat: add link to farcaster user requirement

- cypress/e2e/1-roles-requirements-rewards/0-manage-roles.spec.ts
- src/components/[guild]/DiscordBotPermissionsChecker.tsx
- src/components/[guild]/LeaveButton/LeaveButton.tsx
- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/components/NftDataForm.tsx
- src/platforms/Discord/DiscordCardMenu/DiscordCardMenu.tsx
- src/platforms/Discord/DiscordCardMenu/components/DiscordRewardSettings.tsx.tsx
- src/requirements/Free/FreeRequirement.tsx
- src/requirements/Nft/NftForm.tsx
- src/requirements/Twitter/TwitterForm.tsx
- src/requirements/WalletActivity/WalletActivityForm.tsx
- src/requirements/WalletActivity/WalletActivityRequirement.tsx
- src/requirements/WalletActivity/components/CovalentFirstTx.tsx
- src/requirements/WalletActivity/components/CovalentFirstTxRelative.tsx
- src/requirements/requirements.ts
I'm not really sure about the wallet activity requirement copy, so let me know if you have any suggestions!
> Copy improvements

- src/components/[guild]/AddAndOrderRoles/components/NewRolePlatformCard.tsx
- src/components/[guild]/RoleCard/components/EditRole/components/ExistingRolePlatformCard.tsx
- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddPointsPanel/components/SetPointsAmount/SetPointsAmount.tsx
- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/SelectExistingPlatform.tsx
- src/components/[guild]/RolePlatforms/components/EditRolePlatformModal.tsx
The quick add feature did not show the appropriate edit modal when clicked.
There was also a bug when changing between static and dynamic rewards in the editor.
> fix: quick add dynamic points reward bug

- package-lock.json
- package.json
- src/app/playground/_components/DialogExample.tsx
- src/app/playground/page.tsx
- src/v2/components/ui/Dialog.tsx
Added size variants, will add color variants later!
> feat: `Dialog` component

- package-lock.json
- package.json
- src/app/globals.css
- src/v2/components/ui/Toast.stories.tsx
- src/v2/components/ui/Toast.tsx
- src/v2/components/ui/Toaster.tsx
- src/v2/components/ui/hooks/useToast.ts
- tailwind.config.ts
Implemented a simple toast component. I know we sometimes add icons to our toasts, but for now I haven't implemented that functionality, we can add it once we actually need it.
> feat: `Toast` component & `useToast` hook

- src/requirements/Farcaster/components/FarcasterCast.tsx
- src/requirements/Farcaster/components/FarcasterCastSmall.tsx
- src/requirements/Farcaster/types.ts
> fix(Farcaster): resolve circular dependency

- src/components/create-guild/Requirements/components/AddRequirement.tsx
We should really start using these schemas inside the requirement forms & handle these type of issues inside them, but for now, I think this hotfix do it. Let me know if you have a better idea for it!
> fix(AddRequirement): transform requirement data before parsing

- lint-staged.config.mjs
- next.config.js
- **build: move circular check to vercel only**
- **fix: lint staged**
> biome lint staged fix, move circular import check to vercel

- src/app/globals.css
- src/v2/components/GuildLogo.tsx
- **fix(a11y): adjust primary color to metrics**
- **chore: use css instead of legacy html attr**
> v2 a11y concerns and cleanup

- src/app/explorer/page.tsx
- src/v2/components/Layout/Layout.stories.tsx
- src/v2/components/Layout/Layout.tsx
- src/v2/components/Layout/index.ts
- src/v2/components/ui/Anchor.tsx
- src/v2/components/ui/Avatar.tsx
- src/v2/components/ui/AvatarGroup.tsx
- **chore: adjust v2 components**
- **chore: update Layout on explorer**
> adjust ui v2 components

- biome.json
- **ci: add biome rules**
- **ci: remove noDelete**
> add biome rules

- .github/workflows/code-check.yml
- biome.json
- package-lock.json
- package.json
- src/app/(marketing)/profile/_components/EditProfile/ProfileBackgroundImageUploader.tsx
- src/app/(marketing)/profile/_components/RecentActivity/RewardBadge.tsx
- src/app/globals.css
- src/components/[guild]/JoinModal/utils/mapAccessJobState.ts
- src/components/[guild]/Requirements/components/GuildCheckout/components/BuyTotal.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/PurchaseFeeAndTotal.tsx
- src/components/[guild]/Requirements/components/GuildCheckout/components/TransactionStatusModal/TransactionStatusModal.tsx
- src/components/[guild]/SetVisibility/hooks/useVisibilityTooltipLabel.tsx
- src/components/[guild]/activity/ActivityLogAction/components/UserTag.tsx
- src/components/[guild]/messages/SendNewMessage/SendNewMessage.tsx
- src/components/common/DiscordGuildSetup/DiscordGuildSetup.tsx
- src/hooks/useTokenData.ts
- src/requirements/Nft/NftRequirement.tsx
- src/requirements/Token/TokenRequirement.tsx
- src/requirements/VisitLink/VisitLinkRequirement.tsx
- src/rewards/Gather/hooks/useClaimGather.tsx
- src/rewards/Points/usePointsCardProps.tsx
- src/rewards/SecretText/hooks/useClaimText.tsx
- src/rewards/components/PointsPreview.tsx
- src/rewards/components/PointsReward.tsx
- src/rewards/components/SelectRoleOrSetRequirements.tsx
- src/utils/pluralize.ts
- **style: apply biome write-ci**
- **revert: take back biome ci change**
> fix biome error

- src/app/(marketing)/profile/_components/RecentActivity/ActivityCard.tsx
- src/app/globals.css
- src/v2/components/ui/Badge.stories.ts
- src/v2/components/ui/Badge.tsx
- tailwind.config.ts
We'll need these for the access indicator migration
> feat(Badge): add more color schemes

- package-lock.json
- package.json
- src/app/(marketing)/profile/_components/EditProfile/EditProfile.tsx
- src/app/(marketing)/profile/_components/Profile.tsx
- **chore: update types and add checkbox for activity log**
- **feat: add option to disable recent activities**
> option to hide recent activity

- README.md
Supplementing the name of the social network
> docs: Supplementing the name of the social network

- playwright/05-join-leave.spec.ts
- playwright/constants.ts
- src/components/[guild]/JoinButton.tsx
- src/components/[guild]/JoinModal/JoinModal.tsx
- src/components/[guild]/LeaveButton/LeaveButton.tsx
I managed to break the join flow yesterday by accidentally adding a change to one of my commits, so I wrote tests for joining/leaving a guild - hopefully this way I won't make this kind of mistake in the future...
> feat(playwright): join & leave guild tests

- src/app/terms-of-use/page.tsx
> chore: update terms of use

- src/requirements/Fuel/components/FuelBalance.tsx
Since that's what their graphql api actually checks
> Change fuel token address input to asset id

- src/components/[guild]/AccessHub/components/CampaignCards/CampaignCards.tsx
- src/components/[guild]/Requirements/components/HiddenRequirementAccessIndicator.tsx
> chore: typos correction

- src/lib/schemas/common.ts
- src/lib/schemas/guild.ts
- src/lib/schemas/role.ts
- src/lib/schemas/roleGroup.ts
Added some basic schemas for Guilds, Roles, RoleGroups.
> feat: Guild, Role, RoleGroup schemas

- package.json
- src/app/(dashboard)/create-guild/components/CreateGuildButton.tsx
- src/app/(dashboard)/create-guild/components/CreateGuildFormProvider.tsx
- src/lib/schemas/guild.ts
Removes slugify since it has been moved to backend by https://github.com/guildxyz/guild-backend-v3/pull/14
> remove slugify and adjust guild creation to backend

- package-lock.json
- package.json
- src/components/[guild]/RolePlatforms/components/AddRoleRewardModal/components/AddContractCallPanel/components/CreateNftForm/hooks/useCreateNft.ts
- Discord thread: [dev-talk > Form mainnet](https://discord.com/channels/697041998728659035/1315592336004354139), [forum > Ink](https://discord.com/channels/697041998728659035/1317146480288596018)
Added the chain to useCreateNFT and updated the types package, no es mucho pero es trabajo honesto
> feat: add support for Pin on Ink & Form, NFT reward on Ink

- src/requirements/ContractState/ContractStateForm.tsx
> copy(contractStateForm): add helper text for output param indexes

- .husky/pre-commit
- package-lock.json
- package.json
The pre-push hook never worked for me. This is how we solved it on backend a year ago, thought I would commit it here
> Fix husky for certain setups with nvm
